package com.learn.SpringBootApplication.EmployeeBean;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

//JPA usage involves entity annotation maps the DB column with the Bean attributes
@Entity(name="employee")
public class Employee {
    @Id
    private int id;
    private String name;
    private String location;

    public Employee(){
      //Dummy constructor to prevent the default constructor error generated by RowMapper
    }

    public Employee(int id, String name, String location) {
        this.id = id;
        this.name = name;
        this.location = location;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", location='" + location + '\'' +
                '}';
    }
}
